spring:
  datasource:
    url: jdbc:postgresql://mypostgres:5432/postgres
    username: postgres
    password: cms@spring
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    generate-ddl: true
message:
  topic:
    name: orderItem        

    
  kafka:
    bootstrapAddress: kafka:9093
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      
      
greeting:
  topic:
    name: test